[package]
name = "roguelike"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.19"
env_logger = "0.9.0"
log = "0.4.0"
serde = { version = "1.0.130", features= ["derive"] }
serde_json = "1.0"
tokio = { version = "1.10.0", features = ["full"] }
wgpu = "0.11.0"
winit = "0.25.0"